-- Pre-baked head-focused crop URL. The directory view shows the
-- full photo with object-position centered on the focal point;
-- the shortlist (220 px tall wide band) can't fit a face inside
-- that aspect with only object-position, so we ship a separate
-- derivative that's already tightly cropped around the face.
--
-- Generated by lib/photo-focal/run-batch.ts after face detection
-- using sharp + the detected face bounding box, uploaded to Blob
-- under alumni-headshots/{id}.jpg. NULL → fall back to photo_url
-- with the focal-point crop.
ALTER TABLE alumni
  ADD COLUMN IF NOT EXISTS photo_headshot_url TEXT;
